import {
  BadgeDollarSign,
  Banknote,
  Building2,
  CalendarDays,
  ClipboardCheck,
  FileStack,
  FileText,
  Hourglass,
  LayoutDashboard,
  MapPinned,
  MessageSquare,
  PieChart,
  Receipt,
  ScrollText,
  Settings2,
  ShieldAlert,
  ShieldCheck,
  Stethoscope,
  UserCog,
  Users,
  Wallet,
  HeartPulse,
  Inbox,
  KeyRound,
  GraduationCap,
  type LucideIcon,
} from 'lucide-react';

type Group = 'Overview' | 'Care' | 'Billing' | 'Business' | 'Admin';

/** Sidebar entries; each shows only if the user holds its permission (the API enforces it regardless). */
export const NAVIGATION: readonly { href: string; label: string; permission: string | null; icon: LucideIcon; group: Group }[] = [
  { href: '/', label: 'Dashboard', permission: null, icon: LayoutDashboard, group: 'Overview' },
  { href: '/messages', label: 'Messages', permission: 'messages:use', icon: MessageSquare, group: 'Overview' },
  { href: '/schedule', label: 'Schedule', permission: 'visits:read', icon: CalendarDays, group: 'Care' },
  { href: '/monitor', label: 'Live monitor', permission: 'evv:read', icon: MapPinned, group: 'Care' },
  { href: '/evv', label: 'EVV review', permission: 'evv:read', icon: ShieldCheck, group: 'Care' },
  { href: '/referrals', label: 'Referrals', permission: 'referrals:read', icon: Inbox, group: 'Care' },
  { href: '/patients', label: 'Patients', permission: 'patients:read', icon: HeartPulse, group: 'Care' },
  { href: '/staff', label: 'Staff', permission: 'staff:read', icon: Users, group: 'Care' },
  { href: '/physicians', label: 'Physicians', permission: 'physicians:read', icon: Stethoscope, group: 'Care' },
  { href: '/training', label: 'Academy', permission: 'training:manage', icon: GraduationCap, group: 'Care' },
  { href: '/billing/ready', label: 'Ready to bill', permission: 'billing:read', icon: ClipboardCheck, group: 'Billing' },
  { href: '/billing/claims', label: 'Claims', permission: 'billing:read', icon: FileText, group: 'Billing' },
  { href: '/billing/files', label: 'Claim files', permission: 'billing:read', icon: FileStack, group: 'Billing' },
  { href: '/billing/invoices', label: 'Invoices', permission: 'billing:read', icon: Receipt, group: 'Billing' },
  { href: '/billing/payments', label: 'Payments', permission: 'billing:read', icon: Wallet, group: 'Billing' },
  { href: '/billing/aging', label: 'AR aging', permission: 'billing:read', icon: Hourglass, group: 'Billing' },
  { href: '/billing/setup', label: 'Billing setup', permission: 'billing:read', icon: Settings2, group: 'Billing' },
  { href: '/reports', label: 'Reports', permission: 'reports:read', icon: PieChart, group: 'Business' },
  { href: '/payroll', label: 'Payroll', permission: 'payroll:read', icon: Banknote, group: 'Business' },
  { href: '/my-pay', label: 'My pay', permission: 'visits:read', icon: BadgeDollarSign, group: 'Business' },
  { href: '/compliance', label: 'Compliance', permission: 'compliance:create', icon: ShieldAlert, group: 'Admin' },
  { href: '/compliance/audit-log', label: 'Audit log', permission: 'audit_logs:read', icon: ScrollText, group: 'Admin' },
  { href: '/users', label: 'Users', permission: 'users:read', icon: UserCog, group: 'Admin' },
  { href: '/settings/agency', label: 'Agency settings', permission: 'settings:read', icon: Building2, group: 'Admin' },
  { href: '/settings/roles', label: 'Roles', permission: 'users:read', icon: KeyRound, group: 'Admin' },
];

export const NAV_GROUPS: readonly Group[] = ['Overview', 'Care', 'Billing', 'Business', 'Admin'];
